// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v6.33.4
// source: scalar.proto

package scalarpb

import (
	dtypepb "github.com/mprammer/vortex-go/internal/wire/dtypepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dtype         *dtypepb.DType         `protobuf:"bytes,1,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Value         *ScalarValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalar) Reset() {
	*x = Scalar{}
	mi := &file_scalar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalar) ProtoMessage() {}

func (x *Scalar) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalar.ProtoReflect.Descriptor instead.
func (*Scalar) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{0}
}

func (x *Scalar) GetDtype() *dtypepb.DType {
	if x != nil {
		return x.Dtype
	}
	return nil
}

func (x *Scalar) GetValue() *ScalarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type ScalarValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ScalarValue_NullValue
	//	*ScalarValue_BoolValue
	//	*ScalarValue_Int64Value
	//	*ScalarValue_Uint64Value
	//	*ScalarValue_F32Value
	//	*ScalarValue_F64Value
	//	*ScalarValue_StringValue
	//	*ScalarValue_BytesValue
	//	*ScalarValue_ListValue
	//	*ScalarValue_F16Value
	//	*ScalarValue_VariantValue
	//	*ScalarValue_UnionValue
	Kind          isScalarValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarValue) Reset() {
	*x = ScalarValue{}
	mi := &file_scalar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarValue) ProtoMessage() {}

func (x *ScalarValue) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarValue.ProtoReflect.Descriptor instead.
func (*ScalarValue) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{1}
}

func (x *ScalarValue) GetKind() isScalarValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ScalarValue) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *ScalarValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ScalarValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *ScalarValue) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *ScalarValue) GetF32Value() float32 {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_F32Value); ok {
			return x.F32Value
		}
	}
	return 0
}

func (x *ScalarValue) GetF64Value() float64 {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_F64Value); ok {
			return x.F64Value
		}
	}
	return 0
}

func (x *ScalarValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ScalarValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *ScalarValue) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *ScalarValue) GetF16Value() uint64 {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_F16Value); ok {
			return x.F16Value
		}
	}
	return 0
}

func (x *ScalarValue) GetVariantValue() *Scalar {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_VariantValue); ok {
			return x.VariantValue
		}
	}
	return nil
}

func (x *ScalarValue) GetUnionValue() *UnionValue {
	if x != nil {
		if x, ok := x.Kind.(*ScalarValue_UnionValue); ok {
			return x.UnionValue
		}
	}
	return nil
}

type isScalarValue_Kind interface {
	isScalarValue_Kind()
}

type ScalarValue_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type ScalarValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ScalarValue_Int64Value struct {
	Int64Value int64 `protobuf:"zigzag64,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type ScalarValue_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type ScalarValue_F32Value struct {
	F32Value float32 `protobuf:"fixed32,5,opt,name=f32_value,json=f32Value,proto3,oneof"`
}

type ScalarValue_F64Value struct {
	F64Value float64 `protobuf:"fixed64,6,opt,name=f64_value,json=f64Value,proto3,oneof"`
}

type ScalarValue_StringValue struct {
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ScalarValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,8,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type ScalarValue_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,9,opt,name=list_value,json=listValue,proto3,oneof"`
}

type ScalarValue_F16Value struct {
	F16Value uint64 `protobuf:"varint,10,opt,name=f16_value,json=f16Value,proto3,oneof"`
}

type ScalarValue_VariantValue struct {
	// Variant scalars carry a row-specific nested scalar.
	// See RFC 0015: https://github.com/vortex-data/rfcs/blob/develop/accepted/0015-variant-type.md
	VariantValue *Scalar `protobuf:"bytes,11,opt,name=variant_value,json=variantValue,proto3,oneof"`
}

type ScalarValue_UnionValue struct {
	UnionValue *UnionValue `protobuf:"bytes,12,opt,name=union_value,json=unionValue,proto3,oneof"`
}

func (*ScalarValue_NullValue) isScalarValue_Kind() {}

func (*ScalarValue_BoolValue) isScalarValue_Kind() {}

func (*ScalarValue_Int64Value) isScalarValue_Kind() {}

func (*ScalarValue_Uint64Value) isScalarValue_Kind() {}

func (*ScalarValue_F32Value) isScalarValue_Kind() {}

func (*ScalarValue_F64Value) isScalarValue_Kind() {}

func (*ScalarValue_StringValue) isScalarValue_Kind() {}

func (*ScalarValue_BytesValue) isScalarValue_Kind() {}

func (*ScalarValue_ListValue) isScalarValue_Kind() {}

func (*ScalarValue_F16Value) isScalarValue_Kind() {}

func (*ScalarValue_VariantValue) isScalarValue_Kind() {}

func (*ScalarValue_UnionValue) isScalarValue_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ScalarValue         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_scalar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{2}
}

func (x *ListValue) GetValues() []*ScalarValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// A present union value. Outer-null unions use ScalarValue.null_value instead.
type UnionValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        uint32                 `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Value         *ScalarValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnionValue) Reset() {
	*x = UnionValue{}
	mi := &file_scalar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionValue) ProtoMessage() {}

func (x *UnionValue) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionValue.ProtoReflect.Descriptor instead.
func (*UnionValue) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{3}
}

func (x *UnionValue) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *UnionValue) GetValue() *ScalarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_scalar_proto protoreflect.FileDescriptor

const file_scalar_proto_rawDesc = "" +
	"\n" +
	"\fscalar.proto\x12\x16mprammer.vortex.scalar\x1a\vdtype.proto\x1a\x1cgoogle/protobuf/struct.proto\"w\n" +
	"\x06Scalar\x122\n" +
	"\x05dtype\x18\x01 \x01(\v2\x1c.mprammer.vortex.dtype.DTypeR\x05dtype\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.mprammer.vortex.scalar.ScalarValueR\x05value\"\xb2\x04\n" +
	"\vScalarValue\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x12H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint64_value\x18\x04 \x01(\x04H\x00R\vuint64Value\x12\x1d\n" +
	"\tf32_value\x18\x05 \x01(\x02H\x00R\bf32Value\x12\x1d\n" +
	"\tf64_value\x18\x06 \x01(\x01H\x00R\bf64Value\x12#\n" +
	"\fstring_value\x18\a \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\b \x01(\fH\x00R\n" +
	"bytesValue\x12B\n" +
	"\n" +
	"list_value\x18\t \x01(\v2!.mprammer.vortex.scalar.ListValueH\x00R\tlistValue\x12\x1d\n" +
	"\tf16_value\x18\n" +
	" \x01(\x04H\x00R\bf16Value\x12E\n" +
	"\rvariant_value\x18\v \x01(\v2\x1e.mprammer.vortex.scalar.ScalarH\x00R\fvariantValue\x12E\n" +
	"\vunion_value\x18\f \x01(\v2\".mprammer.vortex.scalar.UnionValueH\x00R\n" +
	"unionValueB\x06\n" +
	"\x04kind\"H\n" +
	"\tListValue\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.mprammer.vortex.scalar.ScalarValueR\x06values\"`\n" +
	"\n" +
	"UnionValue\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\rR\x06typeId\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.mprammer.vortex.scalar.ScalarValueR\x05valueBV\n" +
	"\x10dev.vortex.protoB\fScalarProtosZ4github.com/mprammer/vortex-go/internal/wire/scalarpbb\x06proto3"

var (
	file_scalar_proto_rawDescOnce sync.Once
	file_scalar_proto_rawDescData []byte
)

func file_scalar_proto_rawDescGZIP() []byte {
	file_scalar_proto_rawDescOnce.Do(func() {
		file_scalar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalar_proto_rawDesc), len(file_scalar_proto_rawDesc)))
	})
	return file_scalar_proto_rawDescData
}

var file_scalar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scalar_proto_goTypes = []any{
	(*Scalar)(nil),          // 0: mprammer.vortex.scalar.Scalar
	(*ScalarValue)(nil),     // 1: mprammer.vortex.scalar.ScalarValue
	(*ListValue)(nil),       // 2: mprammer.vortex.scalar.ListValue
	(*UnionValue)(nil),      // 3: mprammer.vortex.scalar.UnionValue
	(*dtypepb.DType)(nil),   // 4: mprammer.vortex.dtype.DType
	(structpb.NullValue)(0), // 5: google.protobuf.NullValue
}
var file_scalar_proto_depIdxs = []int32{
	4, // 0: mprammer.vortex.scalar.Scalar.dtype:type_name -> mprammer.vortex.dtype.DType
	1, // 1: mprammer.vortex.scalar.Scalar.value:type_name -> mprammer.vortex.scalar.ScalarValue
	5, // 2: mprammer.vortex.scalar.ScalarValue.null_value:type_name -> google.protobuf.NullValue
	2, // 3: mprammer.vortex.scalar.ScalarValue.list_value:type_name -> mprammer.vortex.scalar.ListValue
	0, // 4: mprammer.vortex.scalar.ScalarValue.variant_value:type_name -> mprammer.vortex.scalar.Scalar
	3, // 5: mprammer.vortex.scalar.ScalarValue.union_value:type_name -> mprammer.vortex.scalar.UnionValue
	1, // 6: mprammer.vortex.scalar.ListValue.values:type_name -> mprammer.vortex.scalar.ScalarValue
	1, // 7: mprammer.vortex.scalar.UnionValue.value:type_name -> mprammer.vortex.scalar.ScalarValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_scalar_proto_init() }
func file_scalar_proto_init() {
	if File_scalar_proto != nil {
		return
	}
	file_scalar_proto_msgTypes[1].OneofWrappers = []any{
		(*ScalarValue_NullValue)(nil),
		(*ScalarValue_BoolValue)(nil),
		(*ScalarValue_Int64Value)(nil),
		(*ScalarValue_Uint64Value)(nil),
		(*ScalarValue_F32Value)(nil),
		(*ScalarValue_F64Value)(nil),
		(*ScalarValue_StringValue)(nil),
		(*ScalarValue_BytesValue)(nil),
		(*ScalarValue_ListValue)(nil),
		(*ScalarValue_F16Value)(nil),
		(*ScalarValue_VariantValue)(nil),
		(*ScalarValue_UnionValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalar_proto_rawDesc), len(file_scalar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scalar_proto_goTypes,
		DependencyIndexes: file_scalar_proto_depIdxs,
		MessageInfos:      file_scalar_proto_msgTypes,
	}.Build()
	File_scalar_proto = out.File
	file_scalar_proto_goTypes = nil
	file_scalar_proto_depIdxs = nil
}
