// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayStats struct {
	_tab flatbuffers.Table
}

func GetRootAsArrayStats(buf []byte, offset flatbuffers.UOffsetT) *ArrayStats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArrayStats{}
	x.Init(buf, n+offset)
	return x
}

func FinishArrayStatsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsArrayStats(buf []byte, offset flatbuffers.UOffsetT) *ArrayStats {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArrayStats{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedArrayStatsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ArrayStats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayStats) Table() flatbuffers.Table {
	return rcv._tab
}

// / Protobuf serialized ScalarValue
func (rcv *ArrayStats) Min(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ArrayStats) MinLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ArrayStats) MinBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Protobuf serialized ScalarValue
func (rcv *ArrayStats) MutateMin(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ArrayStats) MinPrecision() Precision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Precision(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ArrayStats) MutateMinPrecision(n Precision) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ArrayStats) Max(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ArrayStats) MaxLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ArrayStats) MaxBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ArrayStats) MutateMax(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ArrayStats) MaxPrecision() Precision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Precision(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ArrayStats) MutateMaxPrecision(n Precision) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *ArrayStats) Sum(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ArrayStats) SumLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ArrayStats) SumBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ArrayStats) MutateSum(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ArrayStats) IsSorted() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ArrayStats) MutateIsSorted(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *ArrayStats) IsStrictSorted() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ArrayStats) MutateIsStrictSorted(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *ArrayStats) IsConstant() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ArrayStats) MutateIsConstant(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *ArrayStats) NullCount() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ArrayStats) MutateNullCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

func (rcv *ArrayStats) UncompressedSizeInBytes() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ArrayStats) MutateUncompressedSizeInBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func (rcv *ArrayStats) NanCount() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ArrayStats) MutateNanCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func ArrayStatsStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func ArrayStatsAddMin(builder *flatbuffers.Builder, min flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(min), 0)
}
func ArrayStatsStartMinVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ArrayStatsAddMinPrecision(builder *flatbuffers.Builder, minPrecision Precision) {
	builder.PrependByteSlot(1, byte(minPrecision), 0)
}
func ArrayStatsAddMax(builder *flatbuffers.Builder, max flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(max), 0)
}
func ArrayStatsStartMaxVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ArrayStatsAddMaxPrecision(builder *flatbuffers.Builder, maxPrecision Precision) {
	builder.PrependByteSlot(3, byte(maxPrecision), 0)
}
func ArrayStatsAddSum(builder *flatbuffers.Builder, sum flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(sum), 0)
}
func ArrayStatsStartSumVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ArrayStatsAddIsSorted(builder *flatbuffers.Builder, isSorted bool) {
	builder.PrependBool(isSorted)
	builder.Slot(5)
}
func ArrayStatsAddIsStrictSorted(builder *flatbuffers.Builder, isStrictSorted bool) {
	builder.PrependBool(isStrictSorted)
	builder.Slot(6)
}
func ArrayStatsAddIsConstant(builder *flatbuffers.Builder, isConstant bool) {
	builder.PrependBool(isConstant)
	builder.Slot(7)
}
func ArrayStatsAddNullCount(builder *flatbuffers.Builder, nullCount uint64) {
	builder.PrependUint64(nullCount)
	builder.Slot(8)
}
func ArrayStatsAddUncompressedSizeInBytes(builder *flatbuffers.Builder, uncompressedSizeInBytes uint64) {
	builder.PrependUint64(uncompressedSizeInBytes)
	builder.Slot(9)
}
func ArrayStatsAddNanCount(builder *flatbuffers.Builder, nanCount uint64) {
	builder.PrependUint64(nanCount)
	builder.Slot(10)
}
func ArrayStatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
