// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / An `ArraySpec` describes the type of a particular array.
// /
// / These are identified by a globally unique string identifier, and looked up in the Vortex registry
// / at read-time.
type ArraySpec struct {
	_tab flatbuffers.Table
}

func GetRootAsArraySpec(buf []byte, offset flatbuffers.UOffsetT) *ArraySpec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArraySpec{}
	x.Init(buf, n+offset)
	return x
}

func FinishArraySpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsArraySpec(buf []byte, offset flatbuffers.UOffsetT) *ArraySpec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArraySpec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedArraySpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ArraySpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArraySpec) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArraySpec) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ArraySpecStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ArraySpecAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func ArraySpecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
