// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type CompressionScheme byte

const (
	CompressionSchemeNone CompressionScheme = 0
	CompressionSchemeLZ4  CompressionScheme = 1
	CompressionSchemeZLib CompressionScheme = 2
	CompressionSchemeZStd CompressionScheme = 3
)

var EnumNamesCompressionScheme = map[CompressionScheme]string{
	CompressionSchemeNone: "None",
	CompressionSchemeLZ4:  "LZ4",
	CompressionSchemeZLib: "ZLib",
	CompressionSchemeZStd: "ZStd",
}

var EnumValuesCompressionScheme = map[string]CompressionScheme{
	"None": CompressionSchemeNone,
	"LZ4":  CompressionSchemeLZ4,
	"ZLib": CompressionSchemeZLib,
	"ZStd": CompressionSchemeZStd,
}

func (v CompressionScheme) String() string {
	if s, ok := EnumNamesCompressionScheme[v]; ok {
		return s
	}
	return "CompressionScheme(" + strconv.FormatInt(int64(v), 10) + ")"
}
