// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Definition of a compression scheme.
type CompressionSpec struct {
	_tab flatbuffers.Table
}

func GetRootAsCompressionSpec(buf []byte, offset flatbuffers.UOffsetT) *CompressionSpec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CompressionSpec{}
	x.Init(buf, n+offset)
	return x
}

func FinishCompressionSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCompressionSpec(buf []byte, offset flatbuffers.UOffsetT) *CompressionSpec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CompressionSpec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCompressionSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CompressionSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CompressionSpec) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CompressionSpec) Scheme() CompressionScheme {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return CompressionScheme(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CompressionSpec) MutateScheme(n CompressionScheme) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func CompressionSpecStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CompressionSpecAddScheme(builder *flatbuffers.Builder, scheme CompressionScheme) {
	builder.PrependByteSlot(0, byte(scheme), 0)
}
func CompressionSpecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
