// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

// / The compression mechanism used to compress the buffer.
type Compression byte

const (
	CompressionNone Compression = 0
	CompressionLZ4  Compression = 1
)

var EnumNamesCompression = map[Compression]string{
	CompressionNone: "None",
	CompressionLZ4:  "LZ4",
}

var EnumValuesCompression = map[string]Compression{
	"None": CompressionNone,
	"LZ4":  CompressionLZ4,
}

func (v Compression) String() string {
	if s, ok := EnumNamesCompression[v]; ok {
		return s
	}
	return "Compression(" + strconv.FormatInt(int64(v), 10) + ")"
}
