// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EncryptionSpec struct {
	_tab flatbuffers.Table
}

func GetRootAsEncryptionSpec(buf []byte, offset flatbuffers.UOffsetT) *EncryptionSpec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EncryptionSpec{}
	x.Init(buf, n+offset)
	return x
}

func FinishEncryptionSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEncryptionSpec(buf []byte, offset flatbuffers.UOffsetT) *EncryptionSpec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EncryptionSpec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEncryptionSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EncryptionSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EncryptionSpec) Table() flatbuffers.Table {
	return rcv._tab
}

func EncryptionSpecStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EncryptionSpecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
