// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / The `FileStatistics` object contains file-level statistics for the Vortex file.
type FileStatistics struct {
	_tab flatbuffers.Table
}

func GetRootAsFileStatistics(buf []byte, offset flatbuffers.UOffsetT) *FileStatistics {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileStatistics{}
	x.Init(buf, n+offset)
	return x
}

func FinishFileStatisticsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFileStatistics(buf []byte, offset flatbuffers.UOffsetT) *FileStatistics {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FileStatistics{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFileStatisticsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FileStatistics) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileStatistics) Table() flatbuffers.Table {
	return rcv._tab
}

// / Statistics for each field in the root schema. If the root schema is not a struct, there will
// / be a single entry in this array.
func (rcv *FileStatistics) FieldStats(obj *ArrayStats, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FileStatistics) FieldStatsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / Statistics for each field in the root schema. If the root schema is not a struct, there will
// / be a single entry in this array.
func FileStatisticsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FileStatisticsAddFieldStats(builder *flatbuffers.Builder, fieldStats flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fieldStats), 0)
}
func FileStatisticsStartFieldStatsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FileStatisticsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
