// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A `Layout` is a recursive data structure describing the physical layout of Vortex arrays in random access storage.
// / As a starting, concrete example, the first three Layout encodings are defined as:
// /
// / 1. encoding == 1, `Flat` -> one buffer, zero child Layouts
// / 2. encoding == 2, `Chunked` -> zero buffers, one or more child Layouts (used for chunks of rows)
// / 3. encoding == 3, `Columnar` -> zero buffers, one or more child Layouts (used for columns of structs)
// /
// / The `row_count` represents the number of rows represented by this Layout. This is very useful for
// / pruning the Layout tree based on row filters.
// /
// / The `metadata` field is fully opaque at this layer, and allows the Layout implementation corresponding to
// / `encoding` to embed additional information that may be useful for the reader. For example, the `ChunkedLayout`
// / uses the first byte of the `metadata` array as a boolean to indicate whether the first child Layout represents
// / the statistics table for the other chunks.
type Layout struct {
	_tab flatbuffers.Table
}

func GetRootAsLayout(buf []byte, offset flatbuffers.UOffsetT) *Layout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Layout{}
	x.Init(buf, n+offset)
	return x
}

func FinishLayoutBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLayout(buf []byte, offset flatbuffers.UOffsetT) *Layout {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Layout{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLayoutBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Layout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Layout) Table() flatbuffers.Table {
	return rcv._tab
}

// / The ID of the encoding used for this Layout.
func (rcv *Layout) Encoding() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

// / The ID of the encoding used for this Layout.
func (rcv *Layout) MutateEncoding(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

// / The number of rows of data represented by this Layout.
func (rcv *Layout) RowCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

// / The number of rows of data represented by this Layout.
func (rcv *Layout) MutateRowCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

// / Any additional metadata this layout needs to interpret its children.
// / This does not include data-specific metadata, which the layout should store in a segment.
func (rcv *Layout) Metadata(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Layout) MetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Layout) MetadataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Any additional metadata this layout needs to interpret its children.
// / This does not include data-specific metadata, which the layout should store in a segment.
func (rcv *Layout) MutateMetadata(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

// / The children of this Layout.
func (rcv *Layout) Children(obj *Layout, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Layout) ChildrenLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / The children of this Layout.
// / Identifiers for each `SegmentSpec` of data required by this layout.
func (rcv *Layout) Segments(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Layout) SegmentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / Identifiers for each `SegmentSpec` of data required by this layout.
func (rcv *Layout) MutateSegments(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func LayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func LayoutAddEncoding(builder *flatbuffers.Builder, encoding uint16) {
	builder.PrependUint16Slot(0, encoding, 0)
}
func LayoutAddRowCount(builder *flatbuffers.Builder, rowCount uint64) {
	builder.PrependUint64Slot(1, rowCount, 0)
}
func LayoutAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(metadata), 0)
}
func LayoutStartMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func LayoutAddChildren(builder *flatbuffers.Builder, children flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(children), 0)
}
func LayoutStartChildrenVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LayoutAddSegments(builder *flatbuffers.Builder, segments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(segments), 0)
}
func LayoutStartSegmentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
