// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A `LayoutSpec` describes the type of a particular layout.
// /
// / These are identified by a globally unique string identifier, and looked up in the Vortex registry
// / at read-time.
type LayoutSpec struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutSpec(buf []byte, offset flatbuffers.UOffsetT) *LayoutSpec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutSpec{}
	x.Init(buf, n+offset)
	return x
}

func FinishLayoutSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLayoutSpec(buf []byte, offset flatbuffers.UOffsetT) *LayoutSpec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LayoutSpec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLayoutSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LayoutSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutSpec) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutSpec) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LayoutSpecStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LayoutSpecAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func LayoutSpecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
