// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / The `Postscript` is guaranteed by the file format to never exceed
// / 65528 bytes (i.e., u16::MAX - 8 bytes) in length, and is immediately
// / followed by an 8-byte `EndOfFile` struct.
// /
// / An initial read of a Vortex file defaults to at least 64KB (u16::MAX bytes) and therefore
// / is guaranteed to cover at least the Postscript.
// /
// / The reason for a postscript at all is to ensure minimal but all necessary footer information
// / can be read in two round trips. Since the DType is optional and possibly large, it lives in
// / its own segment. If the footer were arbitrary size, with a pointer to the DType segment, then
// / in the worst case we would need one round trip to read the footer length, one to read the full
// / footer and parse the DType offset, and a third to fetch the DType segment.
// /
// / The segments pointed to by the postscript have inline compression and encryption specs to avoid
// / the need to fetch encryption schemes up-front.
// /
// / New fields must be appended to preserve FlatBuffers field-order compatibility with old readers.
type Postscript struct {
	_tab flatbuffers.Table
}

func GetRootAsPostscript(buf []byte, offset flatbuffers.UOffsetT) *Postscript {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Postscript{}
	x.Init(buf, n+offset)
	return x
}

func FinishPostscriptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPostscript(buf []byte, offset flatbuffers.UOffsetT) *Postscript {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Postscript{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPostscriptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Postscript) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Postscript) Table() flatbuffers.Table {
	return rcv._tab
}

// / Segment containing the root `DType` flatbuffer.
func (rcv *Postscript) Dtype(obj *PostscriptSegment) *PostscriptSegment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PostscriptSegment)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / Segment containing the root `DType` flatbuffer.
// / Segment containing the root `Layout` flatbuffer (required).
func (rcv *Postscript) Layout(obj *PostscriptSegment) *PostscriptSegment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PostscriptSegment)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / Segment containing the root `Layout` flatbuffer (required).
// / Segment containing the file-level `Statistics` flatbuffer.
func (rcv *Postscript) Statistics(obj *PostscriptSegment) *PostscriptSegment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PostscriptSegment)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / Segment containing the file-level `Statistics` flatbuffer.
// / Segment containing the 'Footer' flatbuffer (required)
func (rcv *Postscript) Footer(obj *PostscriptSegment) *PostscriptSegment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PostscriptSegment)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / Segment containing the 'Footer' flatbuffer (required)
// / User-defined metadata segments keyed by string. Keys must be unique, non-empty, and at most
// / 64 UTF-8 bytes; readers reject postscripts that violate these limits.
func (rcv *Postscript) Metadata(obj *PostscriptMetadata, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Postscript) MetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / User-defined metadata segments keyed by string. Keys must be unique, non-empty, and at most
// / 64 UTF-8 bytes; readers reject postscripts that violate these limits.
func PostscriptStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PostscriptAddDtype(builder *flatbuffers.Builder, dtype flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dtype), 0)
}
func PostscriptAddLayout(builder *flatbuffers.Builder, layout flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(layout), 0)
}
func PostscriptAddStatistics(builder *flatbuffers.Builder, statistics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(statistics), 0)
}
func PostscriptAddFooter(builder *flatbuffers.Builder, footer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(footer), 0)
}
func PostscriptAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(metadata), 0)
}
func PostscriptStartMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PostscriptEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
