// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A `PostscriptSegment` describes the location of a segment in the file without referencing any
// / specification objects. That is, encryption and compression are defined inline.
type PostscriptSegment struct {
	_tab flatbuffers.Table
}

func GetRootAsPostscriptSegment(buf []byte, offset flatbuffers.UOffsetT) *PostscriptSegment {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PostscriptSegment{}
	x.Init(buf, n+offset)
	return x
}

func FinishPostscriptSegmentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPostscriptSegment(buf []byte, offset flatbuffers.UOffsetT) *PostscriptSegment {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PostscriptSegment{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPostscriptSegmentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PostscriptSegment) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PostscriptSegment) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PostscriptSegment) Offset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PostscriptSegment) MutateOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *PostscriptSegment) Length() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PostscriptSegment) MutateLength(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *PostscriptSegment) AlignmentExponent() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PostscriptSegment) MutateAlignmentExponent(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *PostscriptSegment) _Compression(obj *CompressionSpec) *CompressionSpec {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CompressionSpec)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PostscriptSegment) _Encryption(obj *EncryptionSpec) *EncryptionSpec {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(EncryptionSpec)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PostscriptSegmentStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PostscriptSegmentAddOffset(builder *flatbuffers.Builder, offset uint64) {
	builder.PrependUint64Slot(0, offset, 0)
}
func PostscriptSegmentAddLength(builder *flatbuffers.Builder, length uint32) {
	builder.PrependUint32Slot(1, length, 0)
}
func PostscriptSegmentAddAlignmentExponent(builder *flatbuffers.Builder, alignmentExponent byte) {
	builder.PrependByteSlot(2, alignmentExponent, 0)
}
func PostscriptSegmentAdd_Compression(builder *flatbuffers.Builder, _Compression flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(_Compression), 0)
}
func PostscriptSegmentAdd_Encryption(builder *flatbuffers.Builder, _Encryption flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(_Encryption), 0)
}
func PostscriptSegmentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
