// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A keyed user-defined metadata segment.
type PostscriptMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsPostscriptMetadata(buf []byte, offset flatbuffers.UOffsetT) *PostscriptMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PostscriptMetadata{}
	x.Init(buf, n+offset)
	return x
}

func FinishPostscriptMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPostscriptMetadata(buf []byte, offset flatbuffers.UOffsetT) *PostscriptMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PostscriptMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPostscriptMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PostscriptMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PostscriptMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PostscriptMetadata) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PostscriptMetadata) Segment(obj *PostscriptSegment) *PostscriptSegment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PostscriptSegment)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PostscriptMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PostscriptMetadataAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func PostscriptMetadataAddSegment(builder *flatbuffers.Builder, segment flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(segment), 0)
}
func PostscriptMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
