// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type Precision byte

const (
	PrecisionInexact Precision = 0
	PrecisionExact   Precision = 1
)

var EnumNamesPrecision = map[Precision]string{
	PrecisionInexact: "Inexact",
	PrecisionExact:   "Exact",
}

var EnumValuesPrecision = map[string]Precision{
	"Inexact": PrecisionInexact,
	"Exact":   PrecisionExact,
}

func (v Precision) String() string {
	if s, ok := EnumNamesPrecision[v]; ok {
		return s
	}
	return "Precision(" + strconv.FormatInt(int64(v), 10) + ")"
}
