// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Primitive struct {
	_tab flatbuffers.Table
}

func GetRootAsPrimitive(buf []byte, offset flatbuffers.UOffsetT) *Primitive {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Primitive{}
	x.Init(buf, n+offset)
	return x
}

func FinishPrimitiveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPrimitive(buf []byte, offset flatbuffers.UOffsetT) *Primitive {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Primitive{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPrimitiveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Primitive) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Primitive) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Primitive) Ptype() PType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return PType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Primitive) MutatePtype(n PType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Primitive) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Primitive) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func PrimitiveStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PrimitiveAddPtype(builder *flatbuffers.Builder, ptype PType) {
	builder.PrependByteSlot(0, byte(ptype), 0)
}
func PrimitiveAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(1, nullable, false)
}
func PrimitiveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
