// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type PType byte

const (
	PTypeU8  PType = 0
	PTypeU16 PType = 1
	PTypeU32 PType = 2
	PTypeU64 PType = 3
	PTypeI8  PType = 4
	PTypeI16 PType = 5
	PTypeI32 PType = 6
	PTypeI64 PType = 7
	PTypeF16 PType = 8
	PTypeF32 PType = 9
	PTypeF64 PType = 10
)

var EnumNamesPType = map[PType]string{
	PTypeU8:  "U8",
	PTypeU16: "U16",
	PTypeU32: "U32",
	PTypeU64: "U64",
	PTypeI8:  "I8",
	PTypeI16: "I16",
	PTypeI32: "I32",
	PTypeI64: "I64",
	PTypeF16: "F16",
	PTypeF32: "F32",
	PTypeF64: "F64",
}

var EnumValuesPType = map[string]PType{
	"U8":  PTypeU8,
	"U16": PTypeU16,
	"U32": PTypeU32,
	"U64": PTypeU64,
	"I8":  PTypeI8,
	"I16": PTypeI16,
	"I32": PTypeI32,
	"I64": PTypeI64,
	"F16": PTypeF16,
	"F32": PTypeF32,
	"F64": PTypeF64,
}

func (v PType) String() string {
	if s, ok := EnumNamesPType[v]; ok {
		return s
	}
	return "PType(" + strconv.FormatInt(int64(v), 10) + ")"
}
