// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A `SegmentSpec` acts as the locator for a buffer within the file.
type SegmentSpec struct {
	_tab flatbuffers.Struct
}

func (rcv *SegmentSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentSpec) Table() flatbuffers.Table {
	return rcv._tab.Table
}

// / Offset relative to the start of the file.
func (rcv *SegmentSpec) Offset() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}

// / Offset relative to the start of the file.
func (rcv *SegmentSpec) MutateOffset(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

// / Length in bytes of the segment.
func (rcv *SegmentSpec) Length() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}

// / Length in bytes of the segment.
func (rcv *SegmentSpec) MutateLength(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

// / Base-2 exponent of the alignment of the segment.
func (rcv *SegmentSpec) AlignmentExponent() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}

// / Base-2 exponent of the alignment of the segment.
func (rcv *SegmentSpec) MutateAlignmentExponent(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *SegmentSpec) _Compression() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(13))
}
func (rcv *SegmentSpec) Mutate_Compression(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(13), n)
}

func (rcv *SegmentSpec) _Encryption() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(14))
}
func (rcv *SegmentSpec) Mutate_Encryption(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(14), n)
}

func CreateSegmentSpec(builder *flatbuffers.Builder, offset uint64, length uint32, alignmentExponent byte, _Compression byte, _Encryption uint16) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint16(_Encryption)
	builder.PrependByte(_Compression)
	builder.PrependByte(alignmentExponent)
	builder.PrependUint32(length)
	builder.PrependUint64(offset)
	return builder.Offset()
}
