// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type Type byte

const (
	TypeNONE          Type = 0
	TypeNull          Type = 1
	TypeBool          Type = 2
	TypePrimitive     Type = 3
	TypeDecimal       Type = 4
	TypeUtf8          Type = 5
	TypeBinary        Type = 6
	TypeStruct_       Type = 7
	TypeList          Type = 8
	TypeExtension     Type = 9
	TypeFixedSizeList Type = 10
	TypeVariant       Type = 11
	TypeUnion         Type = 12
	TypeMap           Type = 13
)

var EnumNamesType = map[Type]string{
	TypeNONE:          "NONE",
	TypeNull:          "Null",
	TypeBool:          "Bool",
	TypePrimitive:     "Primitive",
	TypeDecimal:       "Decimal",
	TypeUtf8:          "Utf8",
	TypeBinary:        "Binary",
	TypeStruct_:       "Struct_",
	TypeList:          "List",
	TypeExtension:     "Extension",
	TypeFixedSizeList: "FixedSizeList",
	TypeVariant:       "Variant",
	TypeUnion:         "Union",
	TypeMap:           "Map",
}

var EnumValuesType = map[string]Type{
	"NONE":          TypeNONE,
	"Null":          TypeNull,
	"Bool":          TypeBool,
	"Primitive":     TypePrimitive,
	"Decimal":       TypeDecimal,
	"Utf8":          TypeUtf8,
	"Binary":        TypeBinary,
	"Struct_":       TypeStruct_,
	"List":          TypeList,
	"Extension":     TypeExtension,
	"FixedSizeList": TypeFixedSizeList,
	"Variant":       TypeVariant,
	"Union":         TypeUnion,
	"Map":           TypeMap,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
