// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Variant struct {
	_tab flatbuffers.Table
}

func GetRootAsVariant(buf []byte, offset flatbuffers.UOffsetT) *Variant {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Variant{}
	x.Init(buf, n+offset)
	return x
}

func FinishVariantBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVariant(buf []byte, offset flatbuffers.UOffsetT) *Variant {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Variant{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVariantBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Variant) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Variant) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Variant) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Variant) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func VariantStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VariantAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func VariantEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
