// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v6.33.4
// source: dtype.proto

package dtypepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PType int32

const (
	PType_U8  PType = 0
	PType_U16 PType = 1
	PType_U32 PType = 2
	PType_U64 PType = 3
	PType_I8  PType = 4
	PType_I16 PType = 5
	PType_I32 PType = 6
	PType_I64 PType = 7
	PType_F16 PType = 8
	PType_F32 PType = 9
	PType_F64 PType = 10
)

// Enum value maps for PType.
var (
	PType_name = map[int32]string{
		0:  "U8",
		1:  "U16",
		2:  "U32",
		3:  "U64",
		4:  "I8",
		5:  "I16",
		6:  "I32",
		7:  "I64",
		8:  "F16",
		9:  "F32",
		10: "F64",
	}
	PType_value = map[string]int32{
		"U8":  0,
		"U16": 1,
		"U32": 2,
		"U64": 3,
		"I8":  4,
		"I16": 5,
		"I32": 6,
		"I64": 7,
		"F16": 8,
		"F32": 9,
		"F64": 10,
	}
)

func (x PType) Enum() *PType {
	p := new(PType)
	*p = x
	return p
}

func (x PType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PType) Descriptor() protoreflect.EnumDescriptor {
	return file_dtype_proto_enumTypes[0].Descriptor()
}

func (PType) Type() protoreflect.EnumType {
	return &file_dtype_proto_enumTypes[0]
}

func (x PType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PType.Descriptor instead.
func (PType) EnumDescriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{0}
}

type Null struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Null) Reset() {
	*x = Null{}
	mi := &file_dtype_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{0}
}

type Bool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullable      bool                   `protobuf:"varint,1,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bool) Reset() {
	*x = Bool{}
	mi := &file_dtype_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{1}
}

func (x *Bool) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Primitive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PType                  `protobuf:"varint,1,opt,name=type,proto3,enum=mprammer.vortex.dtype.PType" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,2,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Primitive) Reset() {
	*x = Primitive{}
	mi := &file_dtype_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Primitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primitive) ProtoMessage() {}

func (x *Primitive) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primitive.ProtoReflect.Descriptor instead.
func (*Primitive) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{2}
}

func (x *Primitive) GetType() PType {
	if x != nil {
		return x.Type
	}
	return PType_U8
}

func (x *Primitive) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Precision     uint32                 `protobuf:"varint,1,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         int32                  `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_dtype_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{3}
}

func (x *Decimal) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Decimal) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Decimal) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Utf8 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullable      bool                   `protobuf:"varint,1,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Utf8) Reset() {
	*x = Utf8{}
	mi := &file_dtype_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Utf8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utf8) ProtoMessage() {}

func (x *Utf8) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utf8.ProtoReflect.Descriptor instead.
func (*Utf8) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{4}
}

func (x *Utf8) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Binary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullable      bool                   `protobuf:"varint,1,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_dtype_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{5}
}

func (x *Binary) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Dtypes        []*DType               `protobuf:"bytes,2,rep,name=dtypes,proto3" json:"dtypes,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_dtype_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{6}
}

func (x *Struct) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Struct) GetDtypes() []*DType {
	if x != nil {
		return x.Dtypes
	}
	return nil
}

func (x *Struct) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementType   *DType                 `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	Nullable      bool                   `protobuf:"varint,2,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_dtype_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{7}
}

func (x *List) GetElementType() *DType {
	if x != nil {
		return x.ElementType
	}
	return nil
}

func (x *List) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type FixedSizeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementType   *DType                 `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedSizeList) Reset() {
	*x = FixedSizeList{}
	mi := &file_dtype_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedSizeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedSizeList) ProtoMessage() {}

func (x *FixedSizeList) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedSizeList.ProtoReflect.Descriptor instead.
func (*FixedSizeList) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{8}
}

func (x *FixedSizeList) GetElementType() *DType {
	if x != nil {
		return x.ElementType
	}
	return nil
}

func (x *FixedSizeList) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FixedSizeList) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Extension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StorageDtype  *DType                 `protobuf:"bytes,2,opt,name=storage_dtype,json=storageDtype,proto3" json:"storage_dtype,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_dtype_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{9}
}

func (x *Extension) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Extension) GetStorageDtype() *DType {
	if x != nil {
		return x.StorageDtype
	}
	return nil
}

func (x *Extension) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullable      bool                   `protobuf:"varint,1,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_dtype_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{10}
}

func (x *Variant) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Union struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Dtypes        []*DType               `protobuf:"bytes,2,rep,name=dtypes,proto3" json:"dtypes,omitempty"`
	TypeIds       []int32                `protobuf:"varint,3,rep,packed,name=type_ids,json=typeIds,proto3" json:"type_ids,omitempty"` // length must equal dtypes.len(); each value must fit in uint8
	Nullable      bool                   `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Union) Reset() {
	*x = Union{}
	mi := &file_dtype_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Union) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Union) ProtoMessage() {}

func (x *Union) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Union.ProtoReflect.Descriptor instead.
func (*Union) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{11}
}

func (x *Union) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Union) GetDtypes() []*DType {
	if x != nil {
		return x.Dtypes
	}
	return nil
}

func (x *Union) GetTypeIds() []int32 {
	if x != nil {
		return x.TypeIds
	}
	return nil
}

func (x *Union) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Map struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyType       *DType                 `protobuf:"bytes,1,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ValueType     *DType                 `protobuf:"bytes,2,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	KeysSorted    bool                   `protobuf:"varint,3,opt,name=keys_sorted,json=keysSorted,proto3" json:"keys_sorted,omitempty"`
	Nullable      bool                   `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Map) Reset() {
	*x = Map{}
	mi := &file_dtype_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{12}
}

func (x *Map) GetKeyType() *DType {
	if x != nil {
		return x.KeyType
	}
	return nil
}

func (x *Map) GetValueType() *DType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

func (x *Map) GetKeysSorted() bool {
	if x != nil {
		return x.KeysSorted
	}
	return false
}

func (x *Map) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type DType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to DtypeType:
	//
	//	*DType_Null
	//	*DType_Bool
	//	*DType_Primitive
	//	*DType_Decimal
	//	*DType_Utf8
	//	*DType_Binary
	//	*DType_Struct
	//	*DType_List
	//	*DType_Extension
	//	*DType_FixedSizeList
	//	*DType_Variant
	//	*DType_Union
	//	*DType_Map
	DtypeType     isDType_DtypeType `protobuf_oneof:"dtype_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DType) Reset() {
	*x = DType{}
	mi := &file_dtype_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DType) ProtoMessage() {}

func (x *DType) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DType.ProtoReflect.Descriptor instead.
func (*DType) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{13}
}

func (x *DType) GetDtypeType() isDType_DtypeType {
	if x != nil {
		return x.DtypeType
	}
	return nil
}

func (x *DType) GetNull() *Null {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Null); ok {
			return x.Null
		}
	}
	return nil
}

func (x *DType) GetBool() *Bool {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Bool); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *DType) GetPrimitive() *Primitive {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Primitive); ok {
			return x.Primitive
		}
	}
	return nil
}

func (x *DType) GetDecimal() *Decimal {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *DType) GetUtf8() *Utf8 {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Utf8); ok {
			return x.Utf8
		}
	}
	return nil
}

func (x *DType) GetBinary() *Binary {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *DType) GetStruct() *Struct {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Struct); ok {
			return x.Struct
		}
	}
	return nil
}

func (x *DType) GetList() *List {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *DType) GetExtension() *Extension {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

func (x *DType) GetFixedSizeList() *FixedSizeList {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_FixedSizeList); ok {
			return x.FixedSizeList
		}
	}
	return nil
}

func (x *DType) GetVariant() *Variant {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Variant); ok {
			return x.Variant
		}
	}
	return nil
}

func (x *DType) GetUnion() *Union {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *DType) GetMap() *Map {
	if x != nil {
		if x, ok := x.DtypeType.(*DType_Map); ok {
			return x.Map
		}
	}
	return nil
}

type isDType_DtypeType interface {
	isDType_DtypeType()
}

type DType_Null struct {
	Null *Null `protobuf:"bytes,1,opt,name=null,proto3,oneof"`
}

type DType_Bool struct {
	Bool *Bool `protobuf:"bytes,2,opt,name=bool,proto3,oneof"`
}

type DType_Primitive struct {
	Primitive *Primitive `protobuf:"bytes,3,opt,name=primitive,proto3,oneof"`
}

type DType_Decimal struct {
	Decimal *Decimal `protobuf:"bytes,4,opt,name=decimal,proto3,oneof"`
}

type DType_Utf8 struct {
	Utf8 *Utf8 `protobuf:"bytes,5,opt,name=utf8,proto3,oneof"`
}

type DType_Binary struct {
	Binary *Binary `protobuf:"bytes,6,opt,name=binary,proto3,oneof"`
}

type DType_Struct struct {
	Struct *Struct `protobuf:"bytes,7,opt,name=struct,proto3,oneof"`
}

type DType_List struct {
	List *List `protobuf:"bytes,8,opt,name=list,proto3,oneof"`
}

type DType_Extension struct {
	Extension *Extension `protobuf:"bytes,9,opt,name=extension,proto3,oneof"`
}

type DType_FixedSizeList struct {
	FixedSizeList *FixedSizeList `protobuf:"bytes,10,opt,name=fixed_size_list,json=fixedSizeList,proto3,oneof"` // This is after `Extension` for backwards compatibility.
}

type DType_Variant struct {
	Variant *Variant `protobuf:"bytes,11,opt,name=variant,proto3,oneof"`
}

type DType_Union struct {
	Union *Union `protobuf:"bytes,12,opt,name=union,proto3,oneof"`
}

type DType_Map struct {
	Map *Map `protobuf:"bytes,13,opt,name=map,proto3,oneof"`
}

func (*DType_Null) isDType_DtypeType() {}

func (*DType_Bool) isDType_DtypeType() {}

func (*DType_Primitive) isDType_DtypeType() {}

func (*DType_Decimal) isDType_DtypeType() {}

func (*DType_Utf8) isDType_DtypeType() {}

func (*DType_Binary) isDType_DtypeType() {}

func (*DType_Struct) isDType_DtypeType() {}

func (*DType_List) isDType_DtypeType() {}

func (*DType_Extension) isDType_DtypeType() {}

func (*DType_FixedSizeList) isDType_DtypeType() {}

func (*DType_Variant) isDType_DtypeType() {}

func (*DType_Union) isDType_DtypeType() {}

func (*DType_Map) isDType_DtypeType() {}

type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to FieldType:
	//
	//	*Field_Name
	FieldType     isField_FieldType `protobuf_oneof:"field_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_dtype_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{14}
}

func (x *Field) GetFieldType() isField_FieldType {
	if x != nil {
		return x.FieldType
	}
	return nil
}

func (x *Field) GetName() string {
	if x != nil {
		if x, ok := x.FieldType.(*Field_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isField_FieldType interface {
	isField_FieldType()
}

type Field_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

func (*Field_Name) isField_FieldType() {}

type FieldPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []*Field               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPath) Reset() {
	*x = FieldPath{}
	mi := &file_dtype_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPath) ProtoMessage() {}

func (x *FieldPath) ProtoReflect() protoreflect.Message {
	mi := &file_dtype_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPath.ProtoReflect.Descriptor instead.
func (*FieldPath) Descriptor() ([]byte, []int) {
	return file_dtype_proto_rawDescGZIP(), []int{15}
}

func (x *FieldPath) GetPath() []*Field {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_dtype_proto protoreflect.FileDescriptor

const file_dtype_proto_rawDesc = "" +
	"\n" +
	"\vdtype.proto\x12\x15mprammer.vortex.dtype\"\x06\n" +
	"\x04Null\"\"\n" +
	"\x04Bool\x12\x1a\n" +
	"\bnullable\x18\x01 \x01(\bR\bnullable\"Y\n" +
	"\tPrimitive\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.mprammer.vortex.dtype.PTypeR\x04type\x12\x1a\n" +
	"\bnullable\x18\x02 \x01(\bR\bnullable\"Y\n" +
	"\aDecimal\x12\x1c\n" +
	"\tprecision\x18\x01 \x01(\rR\tprecision\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x05R\x05scale\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\"\"\n" +
	"\x04Utf8\x12\x1a\n" +
	"\bnullable\x18\x01 \x01(\bR\bnullable\"$\n" +
	"\x06Binary\x12\x1a\n" +
	"\bnullable\x18\x01 \x01(\bR\bnullable\"p\n" +
	"\x06Struct\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x124\n" +
	"\x06dtypes\x18\x02 \x03(\v2\x1c.mprammer.vortex.dtype.DTypeR\x06dtypes\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\"c\n" +
	"\x04List\x12?\n" +
	"\felement_type\x18\x01 \x01(\v2\x1c.mprammer.vortex.dtype.DTypeR\velementType\x12\x1a\n" +
	"\bnullable\x18\x02 \x01(\bR\bnullable\"\x80\x01\n" +
	"\rFixedSizeList\x12?\n" +
	"\felement_type\x18\x01 \x01(\v2\x1c.mprammer.vortex.dtype.DTypeR\velementType\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\"\x8c\x01\n" +
	"\tExtension\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\rstorage_dtype\x18\x02 \x01(\v2\x1c.mprammer.vortex.dtype.DTypeR\fstorageDtype\x12\x1f\n" +
	"\bmetadata\x18\x03 \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"%\n" +
	"\aVariant\x12\x1a\n" +
	"\bnullable\x18\x01 \x01(\bR\bnullable\"\x8a\x01\n" +
	"\x05Union\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x124\n" +
	"\x06dtypes\x18\x02 \x03(\v2\x1c.mprammer.vortex.dtype.DTypeR\x06dtypes\x12\x19\n" +
	"\btype_ids\x18\x03 \x03(\x05R\atypeIds\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\"\xb8\x01\n" +
	"\x03Map\x127\n" +
	"\bkey_type\x18\x01 \x01(\v2\x1c.mprammer.vortex.dtype.DTypeR\akeyType\x12;\n" +
	"\n" +
	"value_type\x18\x02 \x01(\v2\x1c.mprammer.vortex.dtype.DTypeR\tvalueType\x12\x1f\n" +
	"\vkeys_sorted\x18\x03 \x01(\bR\n" +
	"keysSorted\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\"\x85\x06\n" +
	"\x05DType\x121\n" +
	"\x04null\x18\x01 \x01(\v2\x1b.mprammer.vortex.dtype.NullH\x00R\x04null\x121\n" +
	"\x04bool\x18\x02 \x01(\v2\x1b.mprammer.vortex.dtype.BoolH\x00R\x04bool\x12@\n" +
	"\tprimitive\x18\x03 \x01(\v2 .mprammer.vortex.dtype.PrimitiveH\x00R\tprimitive\x12:\n" +
	"\adecimal\x18\x04 \x01(\v2\x1e.mprammer.vortex.dtype.DecimalH\x00R\adecimal\x121\n" +
	"\x04utf8\x18\x05 \x01(\v2\x1b.mprammer.vortex.dtype.Utf8H\x00R\x04utf8\x127\n" +
	"\x06binary\x18\x06 \x01(\v2\x1d.mprammer.vortex.dtype.BinaryH\x00R\x06binary\x127\n" +
	"\x06struct\x18\a \x01(\v2\x1d.mprammer.vortex.dtype.StructH\x00R\x06struct\x121\n" +
	"\x04list\x18\b \x01(\v2\x1b.mprammer.vortex.dtype.ListH\x00R\x04list\x12@\n" +
	"\textension\x18\t \x01(\v2 .mprammer.vortex.dtype.ExtensionH\x00R\textension\x12N\n" +
	"\x0ffixed_size_list\x18\n" +
	" \x01(\v2$.mprammer.vortex.dtype.FixedSizeListH\x00R\rfixedSizeList\x12:\n" +
	"\avariant\x18\v \x01(\v2\x1e.mprammer.vortex.dtype.VariantH\x00R\avariant\x124\n" +
	"\x05union\x18\f \x01(\v2\x1c.mprammer.vortex.dtype.UnionH\x00R\x05union\x12.\n" +
	"\x03map\x18\r \x01(\v2\x1a.mprammer.vortex.dtype.MapH\x00R\x03mapB\f\n" +
	"\n" +
	"dtype_type\"+\n" +
	"\x05Field\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04nameB\f\n" +
	"\n" +
	"field_type\"=\n" +
	"\tFieldPath\x120\n" +
	"\x04path\x18\x01 \x03(\v2\x1c.mprammer.vortex.dtype.FieldR\x04path*h\n" +
	"\x05PType\x12\x06\n" +
	"\x02U8\x10\x00\x12\a\n" +
	"\x03U16\x10\x01\x12\a\n" +
	"\x03U32\x10\x02\x12\a\n" +
	"\x03U64\x10\x03\x12\x06\n" +
	"\x02I8\x10\x04\x12\a\n" +
	"\x03I16\x10\x05\x12\a\n" +
	"\x03I32\x10\x06\x12\a\n" +
	"\x03I64\x10\a\x12\a\n" +
	"\x03F16\x10\b\x12\a\n" +
	"\x03F32\x10\t\x12\a\n" +
	"\x03F64\x10\n" +
	"BT\n" +
	"\x10dev.vortex.protoB\vDTypeProtosZ3github.com/mprammer/vortex-go/internal/wire/dtypepbb\x06proto3"

var (
	file_dtype_proto_rawDescOnce sync.Once
	file_dtype_proto_rawDescData []byte
)

func file_dtype_proto_rawDescGZIP() []byte {
	file_dtype_proto_rawDescOnce.Do(func() {
		file_dtype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtype_proto_rawDesc), len(file_dtype_proto_rawDesc)))
	})
	return file_dtype_proto_rawDescData
}

var file_dtype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dtype_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_dtype_proto_goTypes = []any{
	(PType)(0),            // 0: mprammer.vortex.dtype.PType
	(*Null)(nil),          // 1: mprammer.vortex.dtype.Null
	(*Bool)(nil),          // 2: mprammer.vortex.dtype.Bool
	(*Primitive)(nil),     // 3: mprammer.vortex.dtype.Primitive
	(*Decimal)(nil),       // 4: mprammer.vortex.dtype.Decimal
	(*Utf8)(nil),          // 5: mprammer.vortex.dtype.Utf8
	(*Binary)(nil),        // 6: mprammer.vortex.dtype.Binary
	(*Struct)(nil),        // 7: mprammer.vortex.dtype.Struct
	(*List)(nil),          // 8: mprammer.vortex.dtype.List
	(*FixedSizeList)(nil), // 9: mprammer.vortex.dtype.FixedSizeList
	(*Extension)(nil),     // 10: mprammer.vortex.dtype.Extension
	(*Variant)(nil),       // 11: mprammer.vortex.dtype.Variant
	(*Union)(nil),         // 12: mprammer.vortex.dtype.Union
	(*Map)(nil),           // 13: mprammer.vortex.dtype.Map
	(*DType)(nil),         // 14: mprammer.vortex.dtype.DType
	(*Field)(nil),         // 15: mprammer.vortex.dtype.Field
	(*FieldPath)(nil),     // 16: mprammer.vortex.dtype.FieldPath
}
var file_dtype_proto_depIdxs = []int32{
	0,  // 0: mprammer.vortex.dtype.Primitive.type:type_name -> mprammer.vortex.dtype.PType
	14, // 1: mprammer.vortex.dtype.Struct.dtypes:type_name -> mprammer.vortex.dtype.DType
	14, // 2: mprammer.vortex.dtype.List.element_type:type_name -> mprammer.vortex.dtype.DType
	14, // 3: mprammer.vortex.dtype.FixedSizeList.element_type:type_name -> mprammer.vortex.dtype.DType
	14, // 4: mprammer.vortex.dtype.Extension.storage_dtype:type_name -> mprammer.vortex.dtype.DType
	14, // 5: mprammer.vortex.dtype.Union.dtypes:type_name -> mprammer.vortex.dtype.DType
	14, // 6: mprammer.vortex.dtype.Map.key_type:type_name -> mprammer.vortex.dtype.DType
	14, // 7: mprammer.vortex.dtype.Map.value_type:type_name -> mprammer.vortex.dtype.DType
	1,  // 8: mprammer.vortex.dtype.DType.null:type_name -> mprammer.vortex.dtype.Null
	2,  // 9: mprammer.vortex.dtype.DType.bool:type_name -> mprammer.vortex.dtype.Bool
	3,  // 10: mprammer.vortex.dtype.DType.primitive:type_name -> mprammer.vortex.dtype.Primitive
	4,  // 11: mprammer.vortex.dtype.DType.decimal:type_name -> mprammer.vortex.dtype.Decimal
	5,  // 12: mprammer.vortex.dtype.DType.utf8:type_name -> mprammer.vortex.dtype.Utf8
	6,  // 13: mprammer.vortex.dtype.DType.binary:type_name -> mprammer.vortex.dtype.Binary
	7,  // 14: mprammer.vortex.dtype.DType.struct:type_name -> mprammer.vortex.dtype.Struct
	8,  // 15: mprammer.vortex.dtype.DType.list:type_name -> mprammer.vortex.dtype.List
	10, // 16: mprammer.vortex.dtype.DType.extension:type_name -> mprammer.vortex.dtype.Extension
	9,  // 17: mprammer.vortex.dtype.DType.fixed_size_list:type_name -> mprammer.vortex.dtype.FixedSizeList
	11, // 18: mprammer.vortex.dtype.DType.variant:type_name -> mprammer.vortex.dtype.Variant
	12, // 19: mprammer.vortex.dtype.DType.union:type_name -> mprammer.vortex.dtype.Union
	13, // 20: mprammer.vortex.dtype.DType.map:type_name -> mprammer.vortex.dtype.Map
	15, // 21: mprammer.vortex.dtype.FieldPath.path:type_name -> mprammer.vortex.dtype.Field
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_dtype_proto_init() }
func file_dtype_proto_init() {
	if File_dtype_proto != nil {
		return
	}
	file_dtype_proto_msgTypes[9].OneofWrappers = []any{}
	file_dtype_proto_msgTypes[13].OneofWrappers = []any{
		(*DType_Null)(nil),
		(*DType_Bool)(nil),
		(*DType_Primitive)(nil),
		(*DType_Decimal)(nil),
		(*DType_Utf8)(nil),
		(*DType_Binary)(nil),
		(*DType_Struct)(nil),
		(*DType_List)(nil),
		(*DType_Extension)(nil),
		(*DType_FixedSizeList)(nil),
		(*DType_Variant)(nil),
		(*DType_Union)(nil),
		(*DType_Map)(nil),
	}
	file_dtype_proto_msgTypes[14].OneofWrappers = []any{
		(*Field_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtype_proto_rawDesc), len(file_dtype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtype_proto_goTypes,
		DependencyIndexes: file_dtype_proto_depIdxs,
		EnumInfos:         file_dtype_proto_enumTypes,
		MessageInfos:      file_dtype_proto_msgTypes,
	}.Build()
	File_dtype_proto = out.File
	file_dtype_proto_goTypes = nil
	file_dtype_proto_depIdxs = nil
}
